#!/bin/sh

echo "CiAgICAgICAgIyAgICMgICAgIyMjIyAgICAjIyMjIyAgIyMjIyMjCiAgICAgICAgICMgIyAgICAj
ICAgICMgICAgICMgICAgIwogICAgICAgIyMjICMjIyAgIyAgICAgICAgICAjICAgICMjIyMjCiAg
ICAgICAgICMgIyAgICAjICAgICAgICAgICMgICAgIwogICAgICAgICMgICAjICAgIyAgICAjICAg
ICAjICAgICMKICAgICAgICAgICAgICAgICAjIyMjICAgICAgIyAgICAjCgo=" | base64 -d

mount -t proc none /proc
#mount -t devtmpfs none /dev
mount -t devtmpfs devtmpfs /dev
mount -t sysfs none /sys
mkdir /dev/pts
mount /dev/pts
exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console

insmod /home/pwn/hackme.ko
chmod 777 /dev/hackme

echo 0 > /proc/sys/kernel/dmesg_restrict
echo 0 > /proc/sys/kernel/kptr_restrict

cd /home/pwn
chown -R 1000:1000 .
setsid cttyhack setuidgid 1000 sh

umount /proc
umount /sys
poweroff -f
